image: Visual Studio 2017
configuration: Release

build:
    project: MikuMikuLibrary.sln

artifacts:
    - path: CmdTools/DatabaseConverter/bin/Release
      name: DatabaseConverter
    - path: CmdTools/FarcPack/bin/Release
      name: FarcPack
    - path: CmdTools/TxpConverter/bin/Release
      name: TxpConverter
    - path: MikuMikuLibrary/bin/Release
      name: MikuMikuLibrary
    - path: MikuMikuModel/bin/Release
      name: MikuMikuModel
